### ISSUE TITLE
作間さんと安達でGithubのこのレポジトリの操作のテスト

### ISSUE THREAD

**Issue by adachione** [obata01/groupwork#13]
# modification task

## 問題
作間さんと安達でGithubのこのレポジトリの操作のテスト

## 概要
作間さんと安達でGithubのこのレポジトリの操作のテスト。色々と操作性を確かめてみるだけのテスト

## 期限

以下、完了条件です。

- [x] 作間, 安達
　10/16(金)18時まで

**Comment by kei611** [comment]
あ

**Comment by adachione** [comment]
テスト
